apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress-app
          image: gcr.io/tech-rnd-project/wp-app
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html/
              name: wp-volume
      volumes:
        - name: wp-volume
          persistentVolumeClaim:
            claimName: wp-volume
