kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-app
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  template:
    spec:
      containers:
        - image: gcr.io/tech-rnd-project/wp-app
          name: wordpress-app
          ports:
            - containerPort: 80
    metadata:
      labels:
        app: wordpress-app
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app